### ISSUE TITLE
Computer dictionary

### ISSUE THREAD

**Issue by nikita-moor** [FergusJPWalsh/riddle-arnold#1]
Dear Fergus,

I have compiled your transcript into several [computer dictionary formats](https://latin-dict.github.io/dictionaries/Riddle1864.html).

Feel free to [contact me](https://latin-dict.github.io/about.html) if you find any errors in the description. I will follow the updates of this repository and other your projects.

Best regards,
Nikita

**Comment by FergusJPWalsh** [comment]
Sent you an email!
